sudo: required

services:
  - docker

language: go

go:
  - '1.9'

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=mycoralhealth/corald

after_success:
  - go build -ldflags "-linkmode external -extldflags -static"
  - ldd corald
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - cp /etc/ssl/certs/ca-certificates.crt .
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push $REPO
